### ISSUE TITLE
airsend.kafka.worker.high_2  | [debug] kw_low_640fa35242638 -> Timed out

### ISSUE THREAD

**Issue by gpoveda** [airsend-io/devenv#2]
Hi, 

I'm sorry, I would like to ask you what is the possible issue when I got

airsend.kafka.worker.high_2  | [debug] kw_low_640fa35242638 -> Timed out

I just trying to install devenv by running build and docker composed up ... 

I also have a issue realated with guzzle, but I not sure it is related to kafka:

airsend.cron                 | Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: web (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
airsend.cron                 | Stack trace:
airsend.cron                 | #0 /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
airsend.cron                 | #1 /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
airsend.cron                 | #2 /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
airsend.cron                 | #3 /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
airsend.cron                 | #4  in /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200
airsend.kafka.worker.high_2  | [debug] kw_low_640fa35242638 -> Timed out
airsend.kafka.worker.high_1  | [debug] kw_high_640fa35235870 -> Timed out
airsend.cron                 | Running CRON jobs at 2023-03-13 22:36:01
airsend.cron                 |
airsend.cron                 | Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: web (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
airsend.cron                 | Stack trace:
airsend.cron                 | #0 /var/www/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)

Thank you very much for your attention and help

**Comment by wahshibinharb** [comment]
i don't think somebody alive for it. Tomorrow i gonna try to install. i am hopping someone can hear us to help about it.

**Comment by sullemanhossam** [comment]
> i don't think somebody alive for it. Tomorrow i gonna try to install. i am hopping someone can hear us to help about it.

how did that go for you im trying to get it up aswell as we speak

**Comment by sullemanhossam** [comment]
Lets all keep in touch

https://discord.gg/898qHbyk4z

**Comment by sullemanhossam** [comment]
I got mine running now i use a macbook so its a bit diffrent to you guys the ui is not working im going to migrate all the code over to webpack anyways @wahshibinharb  @gpoveda

**Comment by wahshibinharb** [comment]
I tried on linux server many times but got tons of error and gave it up.. i am glad to hear one person make it work 😁

**Comment by sullemanhossam** [comment]
Brother join the discord perhaps i can help  
     
    
    
     
     
       -- 
      Sent from Canary 
      
      
       
      
     
    
    
    
     
     
       On Sunday, Jun 23, 2024 at 2:36 PM, Wahshi Bin Harb ***@***.***> wrote: 
       
      
      
       
      I tried on linux server many times but got tons of error and gave it up.. i am glad to hear one person make it work 😁 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/airsend-io/devenv/issues/2#issuecomment-2184992620","url": "https://github.com/airsend-io/devenv/issues/2#issuecomment-2184992620","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
